export const ROOT_CHANGED = 'ROOT_CHANGED';
export const LANGUAGE_CHANGED = 'LANGUAGE_CHANGED';

export const LOAD_PIN = 'LOAD_PIN';
export const LOAD_PIN_SUCCESS = 'LOAD_PIN_SUCCESS';
export const LOAD_PIN_FAIL = 'LOAD_PIN_FAIL';

export const LOAD_ALERTS = 'LOAD_ALERTS';
export const LOAD_ALERTS_SUCCESS = 'LOAD_ALERTS_SUCCESS';
export const LOAD_ALERTS_FAIL = 'LOAD_ALERTS_FAIL';

export const LOAD_DIGITAL_CARD = 'LOAD_DIGITAL_CARD';
export const LOAD_DIGITAL_CARD_SUCCESS = 'LOAD_DIGITAL_CARD_SUCCESS';
export const LOAD_DIGITAL_CARD_FAIL = 'LOAD_DIGITAL_CARD_FAIL';

export const LOAD_MEMBER_RESOURCE = 'LOAD_MEMBER_RESOURCE';
export const LOAD_MEMBER_RESOURCE_SUCCESS = 'LOAD_MEMBER_RESOURCE_SUCCESS';
export const LOAD_MEMBER_RESOURCE_FAIL = 'LOAD_MEMBER_RESOURCE_FAIL';

export const SET_PIN = 'SET_PIN';
export const SET_PIN_SUCCESS = 'SET_PIN_SUCCESS';
export const SET_PIN_FAIL = 'SET_PIN_FAIL';

export const PIN = 'PIN';
export const LOGIN = 'LOGIN';
export const MAIN = 'MAIN';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const HOME_REQUEST = 'HOME_REQUEST';
export const HOME_SUCCESS = 'HOME_SUCCESS';
export const HOME_FAIL = 'HOME_FAIL';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';

export const CHECK_USER_EXIST_REQUEST = 'CHECK_USER_EXIST_REQUEST';
export const CHECK_USER_EXIST_SUCCESS = 'CHECK_USER_EXIST_SUCCESS';
export const CHECK_USER_EXIST_FAIL = 'CHECK_USER_EXIST_FAIL';
